version: "3.9"
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'desafio-coodesh'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
  migration:
    build: .
    command: bash -c "yarn prisma migrate dev --name start"
    links:
      - postgres
    depends_on:
      - postgres
volumes:
  postgres-data:
